# Installing Packages
```{r}
library(pageviews)
library(fpp2)
library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)
library(feasts)
```

# Getting Data
```{r}
# Monthly data
obama_pageviews_monthly <- article_pageviews(
  article = "Barack_Obama",
  granularity = "monthly",
  start = "2016010100",
  end = "2023123100"
)

## Average daily views per month
obama_ts <-ts(data = obama_pageviews_monthly$views, start = c(2016,1), frequency = 12)
obama_ts_DA <- obama_ts/monthdays(obama_ts)
obama_ts_DA
autoplot(obama_ts_DA) +
  xlab("Years") + ylab("Views") +
  ggtitle("Average views per day in a month")

# Daily data
obama_pageviews_daily <- article_pageviews(
  article = "Barack_Obama",
  granularity = "daily",
  start = "2016010100",
  end = "2023123100"
)

## Daily timeseries
obama_ts_daily <-ts(data = obama_pageviews_daily$views, start = c(2016,01), frequency = 365.25)
autoplot(obama_ts_daily) +
  xlab("Years") + ylab("Views") +
  ggtitle("Views in a day")
```

# Preprocessing
## Splitting data
```{r}
#train-test split
obama_train_month <- window(obama_ts_DA, start=c(2016, 1), end = c(2021, 12))
obama_test_month <- window(obama_ts_DA, start = c(2022, 1), end = c(2023, 12))

#train-test split daily
obama_train_daily <- window(obama_ts_daily, start = c(2016, 1), end = c(2021, 12))
obama_test_daily <- window(obama_ts_daily, start = c(2022, 1), end = c(2023, 12))
```
## Decomposition using stlf on month
```{r}
autoplot(forecast(stlf(obama_train_month, method = "naive",lambda = "auto")), series = "Naive", PI = FALSE) +
autolayer(forecast(stlf(obama_train_month, method = "rwdrift",lambda = "auto")), series = "Drift", PI = FALSE) +
autolayer(forecast(stlf(obama_train_month, method = "arima",lambda = "auto")), series = "ARIMA", PI = FALSE) +
  ggtitle("Average daily views per month")
```
## Decomposition using stlf on daily
```{r}
autoplot(forecast(stlf(obama_train_daily, method = "naive",lambda = "auto")), series = "Naive", PI = FALSE) +
autolayer(forecast(stlf(obama_train_daily, method = "rwdrift",lambda = "auto")), series = "Drift", PI = FALSE) +
autolayer(forecast(stlf(obama_train_daily, method = "arima",lambda = "auto")), series = "ARIMA", PI = FALSE) +
  ggtitle("Average daily views")
```

# 4 bench mark models
## Monthly
```{r}

```
## Daily
```{r}

```

# MSTL
```{r}
autoplot(mstl(obama_ts_daily))
obama_msts <- msts(obama_ts_daily, seasonal.periods = c(7,12,365.25))
autoplot(obama_msts)
obama_mstl <- (mstl(msts(obama_ts_daily, seasonal.periods = c(7,12,365.25))))
obama_mstl
autoplot(obama_mstl)

#splitting into seasonal and seasonally adjusted
obama_s_adj <- obama_mstl[,2] + obama_mstl[,6]
autoplot(obama_s_adj)

obama_seasonal_weekly <- obama_mstl[,3]
obama_seasonal_monthly <- obama_mstl[,4]
obama_seasonal_yearly <- obama_mstl[,5]

snaive(obama_seasonal_yearly, h = 730.5)
```



#ARIMA Model
```{r}
obama_arima <- auto.arima(obama_s_adj)
#ARIMA(5,0,1) was returned

obama_s_adj_arima_fc <- forecast(obama_arima, h = 730.5)
plot(obama_s_adj_arima_fc)
obama_arima_fc <- obama_s_adj_arima_fc$mean + snaive(obama_seasonal_yearly, h = 730.5)$mean
obama_arima_fc <- ts(obama_arima_fc, start = c(2024, 1), frequency = 365.25)
autoplot(obama_ts_daily) + autolayer(obama_arima_fc)

checkresiduals(obama_s_adj_arima_fc)
```
p-value for residual test returned 4.441e-16, meaning there is significant correlation between the residuals.


#ARIMA-X Model
```{r}
# Daily data for House of Representatives pageviews
dem_pageviews_daily <- article_pageviews(
  article = "Democratic_Party_(United_States)",
  granularity = "daily",
  start = "2016010100",
  end = "2023123100"
)

dem_ts_daily <- ts(data = dem_pageviews_daily$views, start = c(2016,1), frequency = 365.25)
dem_ts_daily

obama_arimax <- auto.arima(obama_s_adj, xreg = dem_ts_daily)
forecast_obama_s_adj <- forecast(obama_arimax, xreg = dem_ts_daily, h = 730.5) 
forecast_obama <- forecast_obama_s_adj$mean + snaive(obama_seasonal_yearly, h = 730.5)$mean
forecast_obama #not sure why this time series starts from (9,3) and ends at (11,2)

```





