install.packages(c("fpp2","dpylr","pageviews","lubridate","jsonlite","httr","ggplot2"))
# Installing Packages
```{r}
library(httr)
library(jsonlite)
library(pageviews)
library(fpp2)
library(dplyr)
library(lubridate)
```
# Project is about US presidential election, looking at page views and trying to predict web traffic
```{r}
2008
Barack Obama (Democrat, Winner) and Joe Biden (Running Mate)
John McCain (Republican) and Sarah Palin (Running Mate)

2012
Barack Obama (Democrat, Winner) and Joe Biden (Running Mate)
Mitt Romney (Republican) and Paul Ryan (Running Mate)

2016
Donald Trump (Republican, Winner) and Mike Pence (Running Mate)
Hillary Clinton (Democrat) and Tim Kaine (Running Mate)

2020
Joe Biden (Democrat, Winner) and Kamala Harris (Running Mate)
Donald Trump (Republican) and Mike Pence (Running Mate)

Election-Related Pages
In addition to the candidate pages, consider analyzing traffic to pages related to the elections themselves and key issues that were prominent during those times:

Pages for each election (e.g., "2008 United States presidential election", "2012 United States presidential election", etc.).
Key political and election issues (e.g., "Healthcare reform in the United States", "United States foreign policy", "Climate change policy of the United States", "Immigration policy of Donald Trump", etc.) during the election years.
Political party pages (e.g., "Democratic Party (United States)", "Republican Party (United States)").
```


# Page Views from January 2008 to July 2016
```{r}
old_pageviews looks at data from January 2008 to July 2016

old_pageviews(
  project = "en.wikipedia",
  platform = "all",
  granularity = "daily",
  start = "2015100100",
  end = "2015101200"
)

pageview_timestamps(timestamps = Sys.Date(), first = TRUE)
# Basic example
r_pageviews <- article_pageviews()
# 2015-07-01 is the earliest it can access


# 2008
## Democrats

# Obama announced that he would run for president in Feb 2007


obama_08_pageviews <- old_pageviews(
  article = "Barack_Obama",
  granularity = "daily",
  start = "2008010100",
  end = "2016083100"
)

tail(obama_08_pageviews)

autoplot(obama_08_pageviews)

obama_pageviews <- article_pageviews(
  article = "Barack_Obama",
  granularity = "monthly",
  start = "2016093000",
  end = "2023123100"
)

head(obama_pageviews)

biden_pageviews <- old_pageviews(
  article = "Joe_Biden",
  granularity = "daily",
  start = "2008010100",
  end = "2016080500"
)
biden_pageviews



democratic_2008_pageviews <- old_pageviews(
  article = "Democratic_Party_(United_States)",
  granularity = "daily",
  start = "2008010100",
  end = "2016080500"
)
democratic_2008_pageviews

## Republicans
John McCain (Republican) and Sarah Palin (Running Mate)

McCain_pageviews <- old_pageviews(
  article = "John_Mccain",
  granularity = "daily",
  start = "2008010100",
  end = "2016080500"
)
McCain_pageviews

Palin_pageviews <- old_pageviews(
  article = "Sarah_Palin",
  granularity = "daily",
  start = "2008010100",
  end = "2016080500"
)
Palin_pageviews

Republican_Party_(United_States)
republican_2008_pageviews <- old_pageviews(
  article = "Republican_Party_(United_States)",
  granularity = "daily",
  start = "2008010100",
  end = "2016080500"
)
republican_2008_pageviews

```

# Other years
```{r}
# 2012

# 2016

# 2020
```